import { existsSync } from 'node:fs';
/**
 * Downloads the public ThndrX (https://x.thndr.app) JavaScript bundle and extracts the API surface:
 * base URLs, endpoint paths, Firebase config and the `x-thndrx-runtime-version`.
 *
 * Usage:
 *   npm run sync:api -- [--out .cache/thndr-bundle] [--report docs/api/endpoints.generated.md]
 *
 * The output report is deterministic (sorted) so `git diff docs/api/endpoints.generated.md` shows exactly what
 * Thndr changed between deployments. Only public static assets are fetched; no credentials are used.
 */
import { mkdir, readFile, writeFile } from 'node:fs/promises';
import { join, resolve } from 'node:path';

const ORIGIN = 'https://x.thndr.app';
const ROUTES = [
  '',
  'auth/login',
  'auth/2fa',
  'auth/verify-email',
  'auth/instructions',
  'workspaces/default/home',
  'workspaces/default/trade',
  'workspaces/default/market',
  'workspaces/watchlists',
  'workspaces/screeners',
  'workspaces/new',
  'mobile/home',
  'mobile/trade',
  'mobile/stock',
  'mobile/market',
  'mobile/account',
  'mobile/settings',
  'webview',
];
const UA = 'Mozilla/5.0 (thndr-mcp bundle sync; +https://github.com/armaaar/thndr-mcp)';

function arg(name: string, fallback: string): string {
  const i = process.argv.indexOf(name);
  return (i > -1 ? process.argv[i + 1] : undefined) ?? fallback;
}

async function get(url: string): Promise<string> {
  const res = await fetch(url, { headers: { 'user-agent': UA } });
  if (!res.ok) throw new Error(`GET ${url} -> ${res.status}`);
  return res.text();
}

async function pool<T>(items: T[], size: number, fn: (item: T) => Promise<void>): Promise<void> {
  const queue = [...items];
  const workers = Array.from({ length: size }, async () => {
    while (queue.length) await fn(queue.shift() as T);
  });
  await Promise.all(workers);
}

/** Parses the webpack runtime's chunk-id → filename map for lazily loaded chunks. */
export function lazyChunkUrls(runtimeSource: string): string[] {
  const m = runtimeSource.match(/static\/chunks\/"\+\(\((\{.*?\})\)\[e\]\|\|e\)\+"\."\+\((\{.*?\})\)\[e\]/s);
  if (!m?.[1] || !m[2]) return [];
  const names: Record<string, string> = Object.fromEntries(
    [...m[1].matchAll(/(\d+):"([^"]+)"/g)].map((x) => [x[1] as string, x[2] as string]),
  );
  return [...m[2].matchAll(/(\d+):"([^"]+)"/g)].map(
    ([, id = '', hash = '']) => `/_next/static/chunks/${names[id] ?? id}.${hash}.js`,
  );
}

/** Extracts API knowledge from concatenated bundle source. */
export interface ApiSurface {
  runtimeVersion: string | null;
  firebase: { apiKey: string | null; authDomain: string | null; projectId: string | null };
  baseUrls: string[];
  paths: string[];
}

export function extract(source: string): ApiSurface {
  const uniq = (xs: string[]) => [...new Set(xs)].sort();
  const paths = uniq(
    [
      ...source.matchAll(
        /["`](\/(?:[a-z0-9-]+-service|portfolio|securities|trading-journals|price-alerts|notifications|savings|thndrx|auth|api\/v2|v[12]\/accounts)[a-zA-Z0-9_/${}.:-]*)["`]/g,
      ),
    ].map((m) => (m[1] ?? '').replace(/\$\{[^}]+\}/g, '{param}')),
  );
  const baseUrls = uniq(
    [...source.matchAll(/baseURL:\s*"([^"]+)"/g)]
      .map((m) => m[1] ?? '')
      .concat(
        [...source.matchAll(/"(https:\/\/[a-z0-9.-]*thndr[a-z0-9.-]*\.(?:app|com)[^"]*)"/g)].map(
          (m) => m[1] ?? '',
        ),
      ),
  ).filter((u) => !/\.(png|jpe?g|svg|webp)$/i.test(u) && !u.includes('thndr-assets'));
  const version = source.match(/\{"rE":\{"major":(\d+),"minor":(\d+),"patch":(\d+)\}\}/);
  const firebase = {
    apiKey: source.match(/apiKey:"(AIza[0-9A-Za-z_-]{35})"/)?.[1] ?? null,
    authDomain: source.match(/authDomain:"([^"]+)"/)?.[1] ?? null,
    projectId: source.match(/projectId:"([^"]+)"/)?.[1] ?? null,
  };
  return {
    runtimeVersion: version ? `${version[1]}.${version[2]}.${version[3]}` : null,
    firebase,
    baseUrls,
    paths,
  };
}

export function renderReport(info: ApiSurface, deploymentId: string | null): string {
  const lines = [
    '# ThndrX API surface (generated)',
    '',
    '> Generated by `npm run sync:api` (.claude/skills/sync-thndr-api/scripts/sync-thndr-bundle.ts) from the public ThndrX bundle. Do not edit by hand.',
    '',
    `- Deployment: \`${deploymentId ?? 'unknown'}\``,
    `- x-thndrx-runtime-version: \`${info.runtimeVersion ?? 'unknown'}\``,
    `- Firebase: project \`${info.firebase.projectId}\`, authDomain \`${info.firebase.authDomain}\`, apiKey \`${info.firebase.apiKey}\``,
    '',
    '## Base URLs',
    '',
    ...info.baseUrls.map((u) => `- ${u}`),
    '',
    `## Paths (${info.paths.length})`,
    '',
    ...info.paths.map((p) => `- \`${p}\``),
    '',
  ];
  return lines.join('\n');
}

async function main() {
  const outDir = resolve(arg('--out', '.cache/thndr-bundle'));
  const report = resolve(arg('--report', 'docs/api/endpoints.generated.md'));
  await mkdir(join(outDir, 'js'), { recursive: true });

  const scripts = new Set<string>();
  let deploymentId: string | null = null;
  for (const route of ROUTES) {
    try {
      const html = await get(`${ORIGIN}/${route}`);
      deploymentId ??= html.match(/data-dpl-id="([^"]+)"/)?.[1] ?? null;
      for (const m of html.matchAll(/\/_next\/static\/[^"?\\]+\.js/g)) scripts.add(m[0]);
    } catch (e) {
      process.stderr.write(`warn: ${(e as Error).message}\n`);
    }
  }
  const runtime = [...scripts].find((s) => /\/webpack-[^/]+\.js$/.test(s));
  if (runtime) for (const u of lazyChunkUrls(await get(ORIGIN + runtime))) scripts.add(u);

  const sources: string[] = [];
  await pool([...scripts], 8, async (u) => {
    const file = join(outDir, 'js', u.replace('/_next/static/', '').replaceAll('/', '_'));
    let body: string;
    if (existsSync(file)) body = await readFile(file, 'utf8');
    else {
      try {
        body = await get(ORIGIN + u);
        await writeFile(file, body);
      } catch (e) {
        process.stderr.write(`warn: ${(e as Error).message}\n`);
        return;
      }
    }
    sources.push(body);
  });

  const info = extract(sources.join('\n'));
  await writeFile(join(outDir, 'surface.json'), `${JSON.stringify({ deploymentId, ...info }, null, 2)}\n`);
  await mkdir(resolve(report, '..'), { recursive: true });
  await writeFile(report, renderReport(info, deploymentId));
  process.stdout.write(
    `Downloaded ${sources.length} chunks (deployment ${deploymentId}). runtime-version=${info.runtimeVersion}, ${info.paths.length} paths.\nReport: ${report}\n`,
  );
}

if (process.argv[1]?.endsWith('sync-thndr-bundle.ts')) {
  main().catch((e) => {
    process.stderr.write(`${(e as Error).stack ?? String(e)}\n`);
    process.exit(1);
  });
}
